package com.cc.easybuy.model;

import com.baomidou.mybatisplus.annotation.TableId;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class EbOrder implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_id
     *
     * @mbggenerated
     */
    @TableId
    private Integer eoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_user_id
     *
     * @mbggenerated
     */
    private String eoUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_user_name
     *
     * @mbggenerated
     */
    private String eoUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_user_address
     *
     * @mbggenerated
     */
    private String eoUserAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_create_time
     *
     * @mbggenerated
     */
    //@TableField(fill = FieldFill.INSERT_UPDATE)
    private Date eoCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_cost
     *
     * @mbggenerated
     */
    private BigDecimal eoCost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_status
     *
     * @mbggenerated
     */
    private Integer eoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column eb_order.eo_type
     *
     * @mbggenerated
     */
    private Integer eoType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table eb_order
     *
     * @mbggenerated
     */

    private static final long serialVersionUID = 1L;

    public Integer getEoId() {
        return eoId;
    }

    public void setEoId(Integer eoId) {
        this.eoId = eoId;
    }

    public String getEoUserId() {
        return eoUserId;
    }

    public void setEoUserId(String eoUserId) {
        this.eoUserId = eoUserId;
    }

    public String getEoUserName() {
        return eoUserName;
    }

    public void setEoUserName(String eoUserName) {
        this.eoUserName = eoUserName;
    }

    public String getEoUserAddress() {
        return eoUserAddress;
    }

    public void setEoUserAddress(String eoUserAddress) {
        this.eoUserAddress = eoUserAddress;
    }

    public Date getEoCreateTime() {
        return eoCreateTime;
    }

    public void setEoCreateTime(Date eoCreateTime) {
        this.eoCreateTime = eoCreateTime;
    }

    public BigDecimal getEoCost() {
        return eoCost;
    }

    public void setEoCost(BigDecimal eoCost) {
        this.eoCost = eoCost;
    }

    public Integer getEoStatus() {
        return eoStatus;
    }

    public void setEoStatus(Integer eoStatus) {
        this.eoStatus = eoStatus;
    }

    public Integer getEoType() {
        return eoType;
    }

    public void setEoType(Integer eoType) {
        this.eoType = eoType;
    }

    @Override
    public String toString() {

        return "EbOrder{" +
                "eoId=" + eoId +
                ", eoUserId='" + eoUserId + '\'' +
                ", eoUserName='" + eoUserName + '\'' +
                ", eoUserAddress='" + eoUserAddress + '\'' +
                ", eoCreateTime=" + eoCreateTime +
                ", eoCost=" + eoCost +
                ", eoStatus=" + eoStatus +
                ", eoType=" + eoType +
                '}';
    }
}